### ISSUE TITLE
Cannot build with neopixels extension

### ISSUE THREAD

**Issue by martinwork** [elecfreaks/pxt-PlanetX#14]
**Describe the bug**

If the Neopixels extension is added with PlanetX, either by the user or as dependency of another extension, the project cannot build.
![image](https://user-images.githubusercontent.com/989126/228280443-caccc71a-f430-42d4-bc11-9dc74551aaa7.png)
There are muliple duplicate definition errors in the browser console.

This was reported to https://support.microbit.org/ (ticket number 61588) by a user trying to use these extensions together
https://github.com/elecfreaks/pxt-PlanetX
https://github.com/elecfreaks/pxt-wukong

For a potential fix, please see the discussion on this PR: https://github.com/microsoft/pxt-microbit/pull/4946

**To Reproduce**
Create new project. Add PlanetX. Add Neopixels or wuKong. Download. See error.

**Expected behavior**
Extensions can be used together.

**Comment by martinwork** [comment]
Thanks @elecfreaks1 What version is this fixed in? It still seems to be a problem in a new project with v1.5.26.
![image](https://github.com/user-attachments/assets/70198cd1-5c2e-418a-84da-c7f20747d2be)

**Comment by martinwork** [comment]
@elecfreaks1 This is not fixed. Cannot build an empty project.

![image](https://github.com/user-attachments/assets/75a206a1-25ab-4986-b6b0-96cc01ab8ae5)

**Comment by martinwork** [comment]
@elecfreaks1 Please reopen.

**Comment by elecfreaks1** [comment]
@martinwork , thanks for pointing out this problem. We have solved it in version v1.5.29. 🫡
