### ISSUE TITLE
Compatibility with micro:bit v2

### ISSUE THREAD

**Issue by microbit-sam** [elecfreaks/pxt-PlanetX#5]
**Describe the bug**
Hi @elecfreaks ,

As you might have seen from microsoft/pxt-microbit#3506 this extension is currently not compiling against the latest version of Micro:bit CODAL. This means it will not work with micro:bit V2.

Software for micro:bit V2 boards is built using CODAL rather than the DAL, and no longer includes the mbed layer. We’ve implemented the most frequently used mbed classes to support easy porting of existing extensions, but there may still be corner cases with this compatibility layer.

As your extension is currently not building, it will be disabled for micro:bit V2. People attempting to use your extension with a micro:bit V2 board will get error 929. This extension will only be re-enabled on micro:bit V2 once it is fixed.

There are details on how to ensure extensions work on both version of the micro:bit here (lancaster-university/codal-microbit-v2#31).

Looking at your extension source I believe that your extension falls under this category:

> 1. Use of mbed APIs that are in the compatibility layer, but no inclusion of mbed.h

**To Reproduce**
Compile a hex file for a micro:bit V2 using: makecode.microbit.org/beta

**Expected behavior**
The extension works on a micro:bit V2

**Comment by lionyhw** [comment]
This is now fixed in release v0.13.1

**Comment by microbit-mark** [comment]
@lionyhw I can confirm that you extension compiles in MakeCode.  Are you happy to close this issue?

**Comment by lionyhw** [comment]
@microbit-mark Thank you for your confirmation. I'll close issues.

**Comment by JaniMobab** [comment]
I've bought a Smart AI Lens from ELECFREAKS, and the version is V2.8.4. I've tried to build a project using the AI Lens but the microbit diplay Init AI lens Error!. I'm using the web-base to download the program and upload the extension from PlanetX AI. Do anyone has a solution to it? Whether it is a version issue? Thank you.
