### ISSUE TITLE
The link to buy the sensors is a dead link. 

### ISSUE THREAD

**Issue by absurdist** [elecfreaks/pxt-PlanetX#6]
Hello,

The link to buy the sensors is a dead link. 

https://www.elecfreaks.com/store/sensor-kit-compatible-with-fischertechnik.html

Is this a discontinued or not released product?

**Comment by lionyhw** [comment]
@absurdist We didn't stop production, The purchase address has changed. You can contact our salesmen: Mark mark@elecfreaks.com
